apiVersion: v1
kind:       Service
metadata:
  name: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app.oam.dev/component: productcatalogservice
  ports:
    - port: 3550
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productcatalogservice
spec:
  host: productcatalogservice
  subsets:
  - labels:
      app.oam.dev/appRevision: product-v1
    name: v1
  - labels:
      app.oam.dev/appRevision: product-v2
    name: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productcatalogservice
spec:
  hosts:
    - productcatalogservice
  http:
    - route:
        - destination:
            host: productcatalogservice
            subset: v1
          weight: 75
        - destination:
            host: productcatalogservice
            subset: v2
          weight: 25