apiVersion: core.oam.dev/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: bikesharing-sc
spec:
  components:
    - componentName: bikesharing-sc-component-v1
      instanceName: bikesharing-app-v1
      traits:
        - name: ingress
          properties:
            hostname: bikesharing-sc.com
            path: /
            servicePort: 80