apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: ck-app
spec:
  components:
    - name: my-ck
      type: clickhouse
      properties:
        storage:
          size: "6Gi"
      traits:
        - type: gateway
          properties:
            class: traefik
            domain: 47.251.8.82.nip.io
            http:
              "/play": 8123
