apiVersion: core.oam.dev/v1alpha1
kind: ComponentSchematic
metadata:
  name: flights-api
spec:
  workloadType: core.oam.dev/v1alpha1.Server
  osType: linux
  arch: amd64
  parameters:
    - name: dataUri
      description: uri for data-api pod
      type: string
      required: true           
  containers:
    - name: flights-api
      image: sonofjorel/rudr-flights-api:0.49   
      env:
        - name: DATA_SERVICE_URI
          value: "foo"
          fromParam: "dataUri"  
      ports:
        - name: http
          containerPort: 3003
          protocol: TCP
