apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apps
spec:
  components:
  - name: apps
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/FogDong/KubeVela-GitOps-Infra-Demo
      secretRef: git-secret
      pullInterval: 1m
      git:
        branch: main
      path: ./apps
      imageRepository:
        image: ghcr.io/fogdong/test-fog
        # secretRef: imagesecret
        filterTags:
          pattern: '^master-[a-f0-9]+-(?P<ts>[0-9]+)'
          extract: '$ts'
        policy:
          numerical:
            order: asc
        commitMessage: "Image: {{range .Updated.Images}}{{println .}}{{end}}"
